name: Java CI with Maven on feature

on:
  push:
    branches: 
      - main
      - develop
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      env:
        API_KEY: ${{ secrets.API_KEY }}
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      env:
        API_KEY: ${{ secrets.API_KEY }}
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
      run: mvn test
    - name: Generate JaCoCo coverage report
      run: mvn jacoco:report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
