name: Java CI with Maven on feature

on:
  push:
    branches: 
          - main
          - 'feature/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      env:
        API_KEY: ${{ secrets.API_KEY }}
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: mvn -B test --file pom.xml
